os:
  - linux
  - osx

language: c
script:
  - make test
  - make test-cpp
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make CFLAGS=-g valgrind; fi
addons:
  apt:
    packages:
      - apache2-utils
      - valgrind
